### ISSUE TITLE
 Strange noise instead of TV effect

### ISSUE THREAD

**Issue by DanilRandom** [BrawlerAce/p4g64.fogrestoration#12]
Having downloaded this mod and installed it via reloaded II, I noticed that instead of the TV effect as in the screenshots, I have a strange noise. I installed only those mods that are listed on the gamebanan page. I'm not good at English, so I use Google Translate, sorry if something is not clear.
![image](https://github.com/user-attachments/assets/e47dac1d-3882-4677-a737-5bbf109983f9)

**Comment by esqwrf** [comment]
Доброго времени суток, я не разраб, но по всей видимости у вас No TV Static 64 находится в порядке загрузки НАД Fog Restoration, а должно быть наоборот (если No TV Static 64 вам вообще нужен). Просто выключите его.

На случай если же в вашем списке нет No TV Static 64, то скорее всего у вас установлена старая версия CEP (Community Enhancement Pack), в которую он был включен.

Надеюсь, помогла (:

**Comment by BrawlerAce** [comment]
The reply by eqswrf is correct. Move No TV Static 64 below P4 Fog Restoration in your mod order in Reloaded-II. However I am working on configuration toggles so you can choose to enable or disable different parts of the mod, including the TV noise.

**Comment by BrawlerAce** [comment]
Late but I did add a configuration toggle and an automatic system to disable the TV static if No TV Static is detected. This was actually added a while ago I just forgot to close this issue lol

**Comment by BrawlerAce** [comment]
Late but I did add a configuration toggle and an automatic system to disable the TV static if No TV Static is detected. This was actually added a while ago I just forgot to close this issue lol
